import type { Metadata } from "next";
import { Poppins, Roboto_Serif } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Navbar from "./components/Navbar";
import Banner from "./components/Banner";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const roboto = Roboto_Serif({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700", "900"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Ecommerce tailwind project ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${roboto.variable} font-poppins container`}
      >
        <Header />
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
